# ========================================================================= 
# ------------------------------------------------------------------------- 
#
#  \date		May 2013
#  \author		TNick
#
#  \brief		Controlls the dependencies of our project
#
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Please read COPYING and README files in root folder
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# ------------------------------------------------------------------------- 
# ========================================================================= 
//
//
//
//
#  INCLUDES    ------------------------------------------------------------ 

source 'https://rubygems.org'

#  INCLUDES    ============================================================ 
//
//
//
//
#  COMMON GEMS    --------------------------------------------------------- 


gem 'rails', '3.2.13'

# To use ActiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'

# jQuerry for rails
gem 'jquery-rails'

# some pretty formatting
gem 'bootstrap-sass', '2.1'

#  COMMON GEMS    ========================================================= 
//
//
//
//
#  DEVELOPMENT    ---------------------------------------------------------

group :development do
  
  # using sqlite in LOCAL MACHINE
  gem 'sqlite3', '1.3.5'
  
  # for testing we're using RSpec
  gem 'rspec-rails', '2.11.0'
  gem 'guard-rspec', '1.2.1'
  
  # add some smart comments about the structure of our tables
  gem 'annotate', '2.5.0'
  
end

#  DEVELOPMENT    =========================================================
//
//
//
//
#  TESTS    ---------------------------------------------------------------

group :test do
  
  # using sqlite in LOCAL MACHINE
  gem 'sqlite3', '1.3.5'
  
  # for testing we're using RSpec
  gem 'rspec-rails', '2.11.0'
  gem 'guard-rspec', '1.2.1'
  
  # easly create database components
  gem 'factory_girl_rails', '4.1.0'
  
end

#  TESTS    ===============================================================
//
//
//
//
# ------------------------------------------------------------------------- 
# ========================================================================= 
